// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrs4gDnUp9BFydQ4Q2gOD7JUyOgHvwY4c',
    appId: '1:906291118551:web:048185621d8265826dcb92',
    messagingSenderId: '906291118551',
    projectId: 'soul-milun',
    authDomain: 'soul-milun.firebaseapp.com',
    databaseURL: 'https://soul-milun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soul-milun.appspot.com',
    measurementId: 'G-9TBKD76B7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIf7I74dxmixPKpBmR0XnRxU0dchbLubE',
    appId: '1:906291118551:android:449030cc3f24fe586dcb92',
    messagingSenderId: '906291118551',
    projectId: 'soul-milun',
    databaseURL: 'https://soul-milun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soul-milun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7puaNxRUhzDil-2L437iGUhN_aOXE684',
    appId: '1:906291118551:ios:cf7889fe95bf50c76dcb92',
    messagingSenderId: '906291118551',
    projectId: 'soul-milun',
    databaseURL: 'https://soul-milun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soul-milun.appspot.com',
    androidClientId: '906291118551-03j1sakfoe4v5ub6qk9kunj6o4kqppq4.apps.googleusercontent.com',
    iosClientId: '906291118551-qljp5iq3s9jbthm6rb3p4k09al6aqfrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.soulMilan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7puaNxRUhzDil-2L437iGUhN_aOXE684',
    appId: '1:906291118551:ios:cf7889fe95bf50c76dcb92',
    messagingSenderId: '906291118551',
    projectId: 'soul-milun',
    databaseURL: 'https://soul-milun-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soul-milun.appspot.com',
    androidClientId: '906291118551-03j1sakfoe4v5ub6qk9kunj6o4kqppq4.apps.googleusercontent.com',
    iosClientId: '906291118551-qljp5iq3s9jbthm6rb3p4k09al6aqfrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.soulMilan',
  );
}
